export const INIT_POST = 'INIT_POST';
export const INIT_POST_SUCCESS = 'INIT_POST_SUCCESS';
export const INIT_POST_ERROR = 'INIT_POST_ERROR';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';

export const SIGN_UP_MASTER = 'SIGN_UP_MASTER';
export const SIGN_UP_MASTER_SUCCESS = 'SIGN_UP_MASTER_SUCCESS';
export const SIGN_IN_MASTER = 'SIGN_IN_MASTER';
export const SIGN_IN_MASTER_SUCCESS = 'SIGN_IN_MASTER_SUCCESS';
export const SIGN_OUT_MASTER = 'SIGN_OUT_MASTER';
export const SIGN_OUT_MASTER_SUCCESS = 'SIGN_OUT_MASTER_SUCCESS';
export const MASTER_LOADED = 'MASTER_LOADED';
export const MASTER_LOADED_SUCCESS = 'MASTER_LOADED_SUCCESS';

export const AUTH_ERROR = 'AUTH_ERROR';
