export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const INIT_POST = 'INIT_POST';
export const INIT_POST_SUCCESS = 'INIT_POST_SUCCESS';
export const INIT_POST_ERROR = 'INIT_POST_ERROR';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR';



export const GET_AUTH_SAGA_USER = 'GET_AUTH_SAGA_USER';
export const GET_AUTH_SAGA_MASTER = 'GET_AUTH_SAGA_MASTER';
export const GET_AUTH = 'GET_AUTH';
export const GET_SIGNIN_SAGA_USER = 'GET_SIGNIN_SAGA_USER';
export const GET_SIGNIN_SAGA_MASTER = 'GET_SIGNIN_SAGA_MASTER';
export const LOGOUT_SAGA = 'LOGOUT_SAGA';
export const GET_LOGOUT = 'GET_LOGOUT';


